version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: "/app/src"
      MONGO_URI: "mongodb://mongodb:27017/apps_db"  # MongoDB connection URI
    volumes:
      - ./src:/app/src  # for live code updates
    deploy:
      replicas: 3  # Scale to 3 replicas
      restart_policy:
        condition: on-failure
    depends_on:
      - mongodb  # Ensures MongoDB starts before the app attempts to connect

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Use a custom Nginx config
    depends_on:
      - app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  # Expose MongoDB's default port
    volumes:
      - ./mongo_data:/data/db  # Persistent data storage
    environment:
      MONGO_INITDB_DATABASE: "apps_db"  # Initialize a default database

volumes:
  mongo_data:  # Persistent volume for MongoDB data
