version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: "/app/src"
    volumes:
      - ./src:/app/src  # for live code updates
    deploy:
      replicas: 3  # Scale to 3 replicas
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Use a custom Nginx config
    depends_on:
      - app
