name: CI for FastAPI Server with Docker and Makefile Tests

on:
  push:
    branches:
      - master
      - "feature/*"
  pull_request:
    branches:
      - master
      - "feature/*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set environment variable from GitHub Secrets
      - name: Set OPENAI_API_KEY environment variable
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      # Step 5: Run tests using Makefile
      - name: Run tests
        run: |
          make tests

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t fastapi-app .

      # Step 3: Run Docker container to ensure it works
      - name: Test Docker container
        run: |
          docker run --rm -d -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} --name fastapi-test -p 8000:8000 fastapi-app
          sleep 5  # Wait for the container to start
          curl -f http://localhost:8000 || (echo "Container failed to start"; exit 1)
          docker stop fastapi-test

  deploy:
      runs-on: ubuntu-latest
      needs: docker
      if: success()  # Only run this job if previous jobs are successful

      steps:
        # Step 1: Checkout the repository
        - name: Checkout code
          uses: actions/checkout@v3

        # Step 2: Set up Heroku CLI
        - name: Set up Heroku CLI
          run: |
            curl https://cli-assets.heroku.com/install.sh | sh
            echo "Heroku CLI installed"

        # Step 3: Authenticate with Heroku using API key
        - name: Authenticate to Heroku
          run: |
            echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token

        # Step 4: Log into the Heroku Container Registry
        - name: Authenticate to Heroku Container Registry
          run: |
            echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

        # Step 5: Build the Docker image for Heroku
        - name: Build Docker image for Heroku
          run: |
            heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}

        # Step 6: Release the Docker image to Heroku
        - name: Release Docker image to Heroku
          run: |
            heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}

        # Step 7: Verify the deployment
        - name: Verify Heroku deployment
          run: |
            curl -f https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com || (echo "Heroku app deployment failed" && exit 1)