name: CI for FastAPI Server with Docker and Makefile Tests

on:
  push:
    branches:
      - master
      - "feature/*"
  pull_request:
    branches:
      - master
      - "feature/*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set environment variable from GitHub Secrets
      - name: Set OPENAI_API_KEY environment variable
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      # Step 5: Run tests using Makefile
      - name: Run tests
        run: |
          make tests

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t fastapi-app .

      # Step 3: Run Docker container to ensure it works
      - name: Test Docker container
        run: |
          docker run --rm -d -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} --name fastapi-test -p 8000:8000 fastapi-app
          sleep 5  # Wait for the container to start
          curl -f http://localhost:8000 || (echo "Container failed to start"; exit 1)
          docker stop fastapi-test
